export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_USER = "CLEAR_USER";
export const GET_FILTERED_USERTYPE = "GET_FILTERED_USERTYPE"
export const SET_ALERT = " SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const ADD_RESULT = 'ADD_RESULT';
export const ERROR_RESULT = 'ERROR_RESULT';

export const GET_QUESTION = "GET_QUESTION";
export const SET_CURRENT_QUESTION = "SET_CURRENT_QUESTION";
export const GET_QUESTIONS = "GET_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";
export const EDIT_QUESTION = "EDIT_QUESTION";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const QUESTION_ERROR = "QUESTION_ERROR";
export const CLEAR_QUESTION = "CLEAR_QUESTION";
export const FILTER_QUESTION = "FILTER_QUESTION";
export const GET_ALL_QUESTIONS = "GET_ALL_QUESTIONS";



export const GET_TEMPLATE = "GET_TEMPLATE";
export const SET_CURRENT_TEMPLATE = "SET_CURRENT_TEMPLATE";
export const GET_TEMPLATES = "GET_TEMPLATES";
export const ADD_TEMPLATE = "ADD_TEMPLATE";
export const TEMPLATE1_GENRATE = "TEMPLATE1_GENRATE";
export const EDIT_TEMPLATE = "EDIT_TEMPLATE";

export const SAVE_FORMDATA1 = "SAVE_FORMDATA1";
export const SAVE_FORMDATA2 = "SAVE_FORMDATA2";
export const SAVE_FORMDATA3 = "SAVE_FORMDATA3";

export const DELETE_TEMPLATE = "DELETE_TEMPLATE";
export const TEMPLATE_ERROR = "TEMPLATE_ERROR";
export const CLEAR_TEMPLATE = "CLEAR_TEMPLATE";
export const FILTER_TEMPLATE = "FILTER_TEMPLATE";
export const GET_ALL_TEMPLATES = "GET_ALL_TEMPLATES";

export const CLEAR_FILTER = "CLEAR_FILTER";

export const GET_ERRORS = 'GET_ERRORS';
export const LOAD_QUIZ = 'LOAD_QUIZ';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_QUIZ_LOADING = 'SET_QUIZ_LOADING';
export const END_FREE_QUIZ = 'END_FREE_QUIZ';
export const CLEAR_QUIZ_STATS = 'CLEAR_QUIZ_STATS';
export const SET_USER_COLOR = 'SET_USER_COLOR';


export const GET_STUDENT = "GET_STUDENT";
export const SET_CURRENT_STUDENT = "SET_CURRENT_STUDENT";
export const GET_STUDENTS = "GET_STUDENTS";
export const ADD_STUDENT = "ADD_STUDENT";
export const EDIT_STUDENT = "EDIT_STUDENT";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const STUDENT_ERROR = "STUDENT_ERROR";
export const CLEAR_STUDENT = "CLEAR_STUDENT";
export const FILTER_STUDENT = "FILTER_STUDENT";
export const GET_ALL_STUDENTS = "GET_ALL_STUDENTS";


export const GET_COURSE = "GET_COURSE";
export const SET_CURRENT_COURSE = "SET_CURRENT_COURSE";
export const GET_COURSES = "GET_COURSES";
export const ADD_COURSE = "ADD_COURSE";
export const EDIT_COURSE = "EDIT_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const COURSE_ERROR = "COURSE_ERROR";
export const CLEAR_COURSE = "CLEAR_COURSE";
export const FILTER_COURSE = "FILTER_COURSE"; 